In [40]:
import numpy as np

In [41]:
x = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
x_array = np.array(x)
print(x,'\n\n')
print(x_array)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
x_array = x_array * 2
print(x_array)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [43]:
print(x_array.mean())

13.0


In [44]:
print(x_array.sum())

156


In [45]:
print(x_array.max())

24


In [46]:
print(x_array.min())

2


In [47]:
y = [[12,11,10,9],[8,7,6,5],[4,3,2,1]]
y_array = np.array(y)
print(x_array,'\n\n')
print(y_array)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]] 


[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [48]:
z_array = x_array*y_array
print(z_array)

[[24 44 60 72]
 [80 84 84 80]
 [72 60 44 24]]


In [49]:
z2_array = y_array/x_array
print(z2_array)

[[6.         2.75       1.66666667 1.125     ]
 [0.8        0.58333333 0.42857143 0.3125    ]
 [0.22222222 0.15       0.09090909 0.04166667]]


In [50]:
z3_array = x_array+y_array
print(z3_array)

[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [51]:
z4_array = x_array-y_array
print(z4_array)

[[-10  -7  -4  -1]
 [  2   5   8  11]
 [ 14  17  20  23]]


In [52]:
y_array_transpose = y_array.T
print(y_array_transpose)

[[12  8  4]
 [11  7  3]
 [10  6  2]
 [ 9  5  1]]


In [53]:
multiplication_matrix = x_array.dot(y_array.T)
print(multiplication_matrix)

[[200 120  40]
 [536 328 120]
 [872 536 200]]


In [54]:
h = [[180,192,186,172,156]]   #in cm
w = [[96,90,45,100,70]]       #in kg
h_array = np.array(h)
w_array = np.array(w)

In [55]:
bmi_array = (w_array)/((h_array/100)**2) ## BMI = weight(in kg)/(height(in m)^2)

In [56]:
print(bmi_array)

[[29.62962963 24.4140625  13.00728408 33.80205516 28.76397107]]


In [57]:
print(bmi_array.shape)
print(x_array.shape)

(1, 5)
(3, 4)


In [58]:
print(bmi_array.size)
print(x_array.size)

5
12
